### ISSUE TITLE
MapReduce used incorrectly in metadata/collate

### ISSUE THREAD

**Issue by colin-nolan** [wtsi-hgi/cookie-monster#12]
Connection of update retriever to CookieJar:
```
def put_update_in_cookie_jar(update_collection: UpdateCollection):
   for update in update_collection:
       enrichment = Enrichment(EnrichmentSource.IRODS_UPDATE, datetime.now(), update.metadata)
       logging.debug("Enriching \"%s\" with: %s" % (update.target, enrichment))
       cookie_jar.enrich_cookie(update.target, enrichment)
```

Sample cookie enrichment:
```
DEBUG:root:Enriching "/iplant/trash/home/testuser/test_upload.bin.copy" with: { timestamp: 2016-01-12 10:20:56.085194, metadata: {'hash': ''}, source: EnrichmentSource.IRODS_UPDATE }
```

Source of runtime error (with added print status):
```
def get_metadata(self, path: str) -> Iterable[Enrichment]:
        '''
        Get all the collected metadata for a file

        @param  path  File path
        @return Iterable[Enrichment]
        '''
        output = []
        results = self.query('metadata', 'collate', key    = path,
                                                    reduce = True,
                                                    group  = True)
        if len(results):
            for enrichment in results.rows[0].value:
                print(enrichment)
                output.append(Enrichment(
                    source    = _to_enrichment_source(enrichment['source']),
                    timestamp = datetime.fromtimestamp(enrichment['timestamp']),
                    metadata  = Metadata(enrichment['metadata'])
                ))

        return sorted(output)
```

Traceback:
```
[{'metadata': {'hash': ''}, 'source': 'irods_update', 'timestamp': 1452519322}, {'metadata': {'hash': ''}, 'source': 'irods_update', 'timestamp': 1452529581}, {'metadata': {'hash': ''}, 'source': 'irods_update', 'timestamp': 1452520939}, {'metadata': {'hash': ''}, 'source': 'irods_update', 'timestamp': 1452517811}]
Exception in thread Thread-15:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cookiemonster/processor/basic_processing.py", line 39, in process
    on_complete(terminate, notifications)
  File "/usr/local/lib/python3.5/dist-packages/cookiemonster/processor/basic_processing.py", line 85, in on_complete
    self.process_any_cookies()
  File "/usr/local/lib/python3.5/dist-packages/cookiemonster/processor/basic_processing.py", line 78, in process_any_cookies
    cookie = self._cookie_jar.get_next_for_processing()
  File "/usr/local/lib/python3.5/dist-packages/cookiemonster/cookiejar/biscuit_tin.py", line 75, in get_next_for_processing
    cookie.enrichments = self._metadata.get_metadata(to_process)
  File "/usr/local/lib/python3.5/dist-packages/cookiemonster/cookiejar/_dbi.py", line 637, in get_metadata
    source    = _to_enrichment_source(enrichment['source']),
TypeError: list indices must be integers or slices, not str
```

**Comment by Xophmeister** [comment]
I can't replicate this: Clearly the above problem is that `enrichment` is the list that ought to be iterated over, but I don't see how `results.rows[0].value` returns anything else: `results` is the return from the CouchDB view, which is of type [`ViewResults`](http://pythonhosted.org/CouchDB/client.html#viewresults), it's reduced so `rows[0]` is all that's there (if anything) with its `value` property. This `value` property is the result of the MapReduce query [`metadata/collate`](https://github.com/wtsi-hgi/cookie-monster/blob/master/cookiemonster/cookiejar/_dbi.py#L645-L665) which will only ever return a (potentially empty) list of dictionaries with `source`, `timestamp` and `metadata` elements... In summary, I don't get how this is happening!

I could not replicate by manually pushing the same thing into the database and then pulling it out. This process correctly returns everything I put in. Likewise, [this test](https://github.com/wtsi-hgi/cookie-monster/blob/master/cookiemonster/tests/cookiejar/test_biscuit_tin.py#L122-L140) does the same thing and doesn't fail.

**Comment by Xophmeister** [comment]
After investigation: This is an artefact of CouchDB's reduce being split up into batches when there are a lot of documents matching the grouping. As a result, you get an array of arrays, rather than just a straight array. According to the [documentation](http://wiki.apache.org/couchdb/Introduction_to_CouchDB_views#Reduce_vs_rereduce), this should be resolved by the client rather than on the DB side, as the reduce function cannot maintain state:

> Therefore, it is wrong to attempt to maintain any sort of state in your reduce function between invocations. And because the Btree node boundaries can appear in any place, it is wrong to attempt to cross-reference adjacent documents too. Any cross-referencing needs to take place in the client, not in a reduce function.

**Comment by colin-nolan** [comment]
It looks like the problem's back...
Source of runtime error (with added print statement):
```
def get_metadata(self, path: str) -> Iterable[Enrichment]:
    '''
    Get all the collected metadata for a file

    @param  path  File path
    @return Iterable[Enrichment]
    '''
    output = []
    results = self.query('metadata', 'collate', key    = path,
                                                reduce = True,
                                                group  = True)
    if len(results):
        data = results.rows[0].value
        if all(isinstance(element, list) for element in data):
            # If a rereduction has occurred, flatten the list of lists
            data = itertools.chain.from_iterable(data)

        for enrichment in data:
            print(enrichment)
            output.append(Enrichment(
                source    = _to_enrichment_source(enrichment['source']),
                timestamp = datetime.fromtimestamp(enrichment['timestamp']),
                metadata  = Metadata(enrichment['metadata'])
            ))

    return sorted(output)
```

Traceback:
```
DEBUG:root:Enriching "/iplant/home/rods/temp2" with: { source: EnrichmentSource.IRODS_UPDATE, timestamp: 2016-01-12 15:14:51.070339, metadata: {'key3': 'value3'} }
[{'timestamp': 1452609260, 'metadata': {'key1': 'value1'}, 'source': 'irods_update'}, {'timestamp': 1452610971, 'metadata': {'key1': 'value1'}, 'source': 'irods_update'}]
Exception in thread Thread-15:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cookiemonster/processor/basic_processing.py", line 39, in process
    on_complete(terminate, notifications)
  File "/usr/local/lib/python3.5/dist-packages/cookiemonster/processor/basic_processing.py", line 85, in on_complete
    self.process_any_cookies()
  File "/usr/local/lib/python3.5/dist-packages/cookiemonster/processor/basic_processing.py", line 78, in process_any_cookies
    cookie = self._cookie_jar.get_next_for_processing()
  File "/usr/local/lib/python3.5/dist-packages/cookiemonster/cookiejar/biscuit_tin.py", line 102, in get_next_for_processing
    cookie.enrichments = self._metadata.get_metadata(to_process)
  File "/usr/local/lib/python3.5/dist-packages/cookiemonster/cookiejar/_dbi.py", line 643, in get_metadata
    source    = _to_enrichment_source(enrichment['source']),
TypeError: list indices must be integers or slices, not str
```

**Comment by Xophmeister** [comment]
What is the value of `results.rows[0].value` before it (presumably) gets flattened?

That said, I believe MapReduce is the wrong approach here. Reading the documentation implies that one shouldn't use the reduce function in the way I am (as it's not "reducing"!). Indeed, if I add a lot of enrichments to one file, the collation view starts to fail with a `reduce_overflow_error`...

**Comment by colin-nolan** [comment]
```
def get_metadata(self, path: str) -> Iterable[Enrichment]:
        '''
        Get all the collected metadata for a file

        @param  path  File path
        @return Iterable[Enrichment]
        '''
        output = []
        results = self.query('metadata', 'collate', key    = path,
                                                    reduce = True,
                                                    group  = True)
        if len(results):
            data = results.rows[0].value
            print(data)
            if all(isinstance(element, list) for element in data):
                # If a rereduction has occurred, flatten the list of lists
                data = itertools.chain.from_iterable(data)

            for enrichment in data:
                print(enrichment)
                output.append(Enrichment(
                    source    = _to_enrichment_source(enrichment['source']),
                    timestamp = datetime.fromtimestamp(enrichment['timestamp']),
                    metadata  = Metadata(enrichment['metadata'])
                ))

        return sorted(output)
```

```
DEBUG:root:Enriching "/iplant/trash/home/testuser/test_upload.bin" with: { timestamp: 2016-01-12 15:46:19.854417, metadata: {'hash': ''}, source: EnrichmentSource.IRODS_UPDATE }
[[[{'timestamp': 1452609260, 'metadata': {'key1': 'value1'}, 'source': 'irods_update'}, {'timestamp': 1452610971, 'metadata': {'key1': 'value1'}, 'source': 'irods_update'}], [{'timestamp': 1452611194, 'metadata': {'key1': 'value1'}, 'source': 'irods_update'}, {'timestamp': 1452611280, 'metadata': {'key1': 'value1'}, 'source': 'irods_update'}, {'timestamp': 1452610607, 'metadata': {'key1': 'value1'}, 'source': 'irods_update'}, {'timestamp': 1452611690, 'metadata': {'key1': 'value1'}, 'source': 'irods_update'}, {'timestamp': 1452611475, 'metadata': {'key1': 'value1'}, 'source': 'irods_update'}]], [{'timestamp': 1452611967, 'metadata': {'key1': 'value1'}, 'source': 'irods_update'}, {'timestamp': 1452611364, 'metadata': {'key1': 'value1'}, 'source': 'irods_update'}, {'timestamp': 1452611173, 'metadata': {'key1': 'value1'}, 'source': 'irods_update'}, {'timestamp': 1452611189, 'metadata': {'key1': 'value1'}, 'source': 'irods_update'}, {'timestamp': 1452608596, 'metadata': {'key1': 'value1'}, 'source': 'irods_update'}, {'timestamp': 1452610020, 'metadata': {'key1': 'value1'}, 'source': 'irods_update'}, {'timestamp': 1452608589, 'metadata': {'key1': 'value1'}, 'source': 'irods_update'}, {'timestamp': 1452611382, 'metadata': {'key1': 'value1'}, 'source': 'irods_update'}, {'timestamp': 1452611182, 'metadata': {'key1': 'value1'}, 'source': 'irods_update'}, {'timestamp': 1452611661, 'metadata': {'key1': 'value1'}, 'source': 'irods_update'}, {'timestamp': 1452606082, 'metadata': {'key1': 'value1'}, 'source': 'irods_update'}, {'timestamp': 1452610655, 'metadata': {'key1': 'value1'}, 'source': 'irods_update'}, {'timestamp': 1452608780, 'metadata': {'key1': 'value1'}, 'source': 'irods_update'}, {'timestamp': 1452608521, 'metadata': {'key1': 'value1'}, 'source': 'irods_update'}, {'timestamp': 1452609435, 'metadata': {'key1': 'value1'}, 'source': 'irods_update'}]]
[{'timestamp': 1452609260, 'metadata': {'key1': 'value1'}, 'source': 'irods_update'}, {'timestamp': 1452610971, 'metadata': {'key1': 'value1'}, 'source': 'irods_update'}]
Exception in thread Thread-18:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cookiemonster/processor/basic_processing.py", line 39, in process
    on_complete(terminate, notifications)
  File "/usr/local/lib/python3.5/dist-packages/cookiemonster/processor/basic_processing.py", line 85, in on_complete
    self.process_any_cookies()
  File "/usr/local/lib/python3.5/dist-packages/cookiemonster/processor/basic_processing.py", line 78, in process_any_cookies
    cookie = self._cookie_jar.get_next_for_processing()
  File "/usr/local/lib/python3.5/dist-packages/cookiemonster/cookiejar/biscuit_tin.py", line 102, in get_next_for_processing
    cookie.enrichments = self._metadata.get_metadata(to_process)
  File "/usr/local/lib/python3.5/dist-packages/cookiemonster/cookiejar/_dbi.py", line 644, in get_metadata
    source    = _to_enrichment_source(enrichment['source']),
TypeError: list indices must be integers or slices, not str
```

**Comment by Xophmeister** [comment]
Lists of lists of lists... perverse :stuck_out_tongue:
