### ISSUE TITLE
`Flask` raises an exception in an `TestElmo` test case

### ISSUE THREAD

**Issue by colin-nolan** [wtsi-hgi/cookie-monster#8]
Despite all tests passing, flask is raising an exception during one of the `TestElmo` tests.

Error:
```
ERROR:elmo:Exception on /869936da560749f5a8f9c716c2f634d7 [POST]
Traceback (most recent call last):
  File "/Users/cn13/homebrew/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/cn13/homebrew/lib/python3.5/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/Users/cn13/homebrew/lib/python3.5/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
```

**Comment by Xophmeister** [comment]
I _think_ Flask is supposed to do that: That is the "secret shutdown route", which is defined with a `POST` handler that calls an internal function to shutdown the server. As such, there's no real need for it to return a response and instead you just get a `500 Internal Server Error` and then the thing shuts down.

For the sake of tidying up the exceptions, I can make it return a response, but it's not worth worrying about.
